/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_smartcard_terminals_ASSDTerminal */

#ifndef _Included_android_smartcard_terminals_ASSDTerminal
#define _Included_android_smartcard_terminals_ASSDTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_smartcard_terminals_ASSDTerminal
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_smartcard_terminals_ASSDTerminal_Close
  (JNIEnv *, jclass);

/*
 * Class:     android_smartcard_terminals_ASSDTerminal
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_smartcard_terminals_ASSDTerminal_Open
  (JNIEnv *, jclass);

/*
 * Class:     android_smartcard_terminals_ASSDTerminal
 * Method:    IsPresent
 * Signature: ()Z
 */
JNIEXPORT
jboolean JNICALL Java_android_smartcard_terminals_ASSDTerminal_IsPresent
  (JNIEnv *, jclass);

/*
 * Class:     android_smartcard_terminals_ASSDTerminal
 * Method:    Transmit
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_smartcard_terminals_ASSDTerminal_Transmit
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
